### ISSUE TITLE
Mildomのwebsocketに接続する際にエラーが発生する

### ISSUE THREAD

**Issue by ryu-s** [CommentViewerCollection/MultiCommentViewer#178]
![image](https://user-images.githubusercontent.com/4012901/132094184-c7a8d4f6-6fca-413f-aa20-f2fc29b3a769.png)

スタックトレース
```
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SitePluginCommon.AutoReconnection.ConnectionManager.<FinishProviderAsync>d__8.MoveNext() in D:\workspace\MultiCommentViewer\SitePluginCommon\AutoReconnection\ConnectionManager.cs:line 86
```

**Comment by ryu-s** [comment]
多分同じエラー？
https://github.com/kerryjiang/WebSocket4Net/issues/178

**Comment by ryu-s** [comment]
修正完了 89bb3c50ccd5e6439c7e535ef5a7dbb7e68c2576
